name: Deploy prod

on: workflow_dispatch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        id: api
        run: |
          resp=$(curl -X POST \
            --url ${{secrets.URL}} \
            -H 'Content-type: application/json' \
            -d '{"project": "astro-bot", "token": "${{secrets.TOKEN}}"}')
          echo OUT_RESP=$resp >> $GITHUB_OUTPUT
      - name: Check output var
        run: |
          echo -e "${{steps.api.outputs.OUT_RESP}}"