name: Deploy prod

on: workflow_dispatch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        run: |
          curl -s --request POST \
          --url ${{secrets.URL}} \
          --header 'content-type: application/json' \
          --data '{"project": "astro-bot", "token": "{{secrets.TOKEN}}"}' >> $GITHUB_OUTPUT
